name = "solana-worker"
main = "index.js"
compatibility_date = "2024-09-15"

# Cron trigger to keep the system alive 24/7 - runs every 2 minutes
[triggers]
crons = ["*/2 * * * *"]

[vars]
NODE_ENV = "production"

[[durable_objects.bindings]]
name = "PUMPPORTAL_TRACKER"
class_name = "PumpPortalTracker"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PumpPortalTracker"]